// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_4JN900yK1hEIEURHFMt-i6t5vkccIHs',
    appId: '1:72922155204:web:02bd9461edadd825856191',
    messagingSenderId: '72922155204',
    projectId: 'crypto-list-app-42abc',
    authDomain: 'crypto-list-app-42abc.firebaseapp.com',
    storageBucket: 'crypto-list-app-42abc.appspot.com',
    measurementId: 'G-F2EXKC1RH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZRpSS4ahMgNxa99ujUhbmPuzh9o5G_c',
    appId: '1:72922155204:android:6e12317f1199c734856191',
    messagingSenderId: '72922155204',
    projectId: 'crypto-list-app-42abc',
    storageBucket: 'crypto-list-app-42abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZ6Gz1jKt3cElNLg4RzmRYJnyeeWapNI',
    appId: '1:72922155204:ios:837b13f16d58b043856191',
    messagingSenderId: '72922155204',
    projectId: 'crypto-list-app-42abc',
    storageBucket: 'crypto-list-app-42abc.appspot.com',
    iosBundleId: 'com.example.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGZ6Gz1jKt3cElNLg4RzmRYJnyeeWapNI',
    appId: '1:72922155204:ios:ef1ede643c8bb65d856191',
    messagingSenderId: '72922155204',
    projectId: 'crypto-list-app-42abc',
    storageBucket: 'crypto-list-app-42abc.appspot.com',
    iosBundleId: 'com.example.cryptoCoinsList.RunnerTests',
  );
}
